
# Selenium
CLICK_TIMEOUT = 40
SCROLL_TIMEOUT = 20
HORIZONTAL_SCROLL_TIMEOUT = 1
TEXT_TIMEOUT = 30
DD_TIMEOUT = 50
DEFAULT_TIMEOUT = 10
TABLE_TIMEOUT = 60
MAX_IMPLICIT_TIMEOUT=4
MIN_IMPLICIT_TIMEOUT=2
POPUP_TIMEOUT = 5
MAXIMUM_TIMEOUT = 500
