name: Selenium Test Automation

on:
  push:
    branches:
      - main  # Runs tests on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Executes tests in a cloud-based Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Set Up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change this based on your project JDK version

      - name: Set Up Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver
          echo "Chrome and ChromeDriver installed"

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Run Tests
        run: mvn clean test
        working-directory: ./SeleniumJava/seleniumtestngframework  # Point to the folder with the pom.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: ./SeleniumJava/seleniumtestngframework/reports/extent-report  # Adjust if reports are inside this folder
