name: Selenium Test Automation

on:
  push:
    branches:
      - main  # Runs tests on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Executes tests in a cloud-based Linux machine

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone Asia/Kolkata
        
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Set Up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Or your desired JDK version

      - name: Set Up Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver
          echo "Chrome and ChromeDriver installed"

      - name: Clean Maven Cache
        run: mvn dependency:purge-local-repository
        

      - name: Run Sanity Suite
        run: mvn clean test -Dsurefire.suiteXmlFiles=smoke_suite.xml -Dgroups=smoke
        working-directory: ./Selenium_Java/seleniumtestngframework  # Point to the folder with the pom.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: ./Selenium_Java/seleniumtestngframework/reports/extent-report
