name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone Asia/Kolkata

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java with Caching
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'  # Enable Maven dependency caching

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver
          echo "Chrome and ChromeDriver installed"

      - name: Set Secret Key as Environment Variable
        run: echo "SECRET_TEST_DATA_KEY=${{ secrets.SECRET_TEST_DATA_KEY }}" >> $GITHUB_ENV

      - name: Run Smoke and Sanity Tests
        run: |
          mvn clean test -Dsurefire.suiteXmlFiles=smoke_suite.xml -Dgroups=smoke
          mvn test -Dsurefire.suiteXmlFiles=sanity_suite.xml -Dgroups=sanity
        working-directory: ./Selenium_Java/seleniumtestngframework

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: ./Selenium_Java/seleniumtestngframework/reports/extent-report
